version: '3.4'
services:
  identifier:
  dispatcher:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  triplestore:
    ports:
      - "8890:8890"
  musearch:
    environment:
      LOG_LEVEL: "debug"
      RACK_ENV: "development"
  deltanotifier:
  elasticsearch:
  kibana:
    ports:
      - "5601:5601"
  resource:
  file:
  range-file:
  document-conversion:
  session-number-service:
  agenda-sort-service:
  custom-subcases-service:
  document-grouping-service:
  file-bundling-service:
  agenda-approve-service:
  mocklogin:
    image: kanselarij/mock-login-service
  login:
  newsletter-service:
  minister-jurisdiction-service:
    environment:
      NODE_ENV: "development"
  yggdrasil:
  user-management-service:
  cache:
