version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  development-identifier:
    container_name: development-kaleidos_backend
    image: semtech/mu-identifier:1.5.0
    links:
      - development-dispatcher:dispatcher
    ports:
      - "8090:80"
    networks:
      - proxy
      - default
      - backend
    environment:
      - VIRTUAL_HOST=dev-kaleidos-backend.kanselarij-dev.s.redpencil.io
      - VIRTUAL_PORT=80
  development-dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - development-resource:resource
    volumes:
      - ./config/devdispatcher:/config
    networks:
      - proxy
      - default
      - backend
  database-with-auth:
    image: semtech/mu-authorization:latest
    environment:
      MU_SPARQL_ENDPOINT: "http://development-database:8890/sparql"
      # LOG_OUTGOING_SPARQL_QUERIES: "true"
      # INSPECT_OUTGOING_SPARQL_QUERIES: "false"
      # LOG_INCOMING_SPARQL_QUERIES: "true"
      # INSPECT_INCOMING_SPARQL_QUERIES: "false"
      # LOG_ACCESS_RIGHTS: "true"
      # INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      # LOG_DELTA_MESSAGES: "true"
      # LOG_DELTA_CLIENT_COMMUNICATION: "true"
      # LOG_TEMPLATE_MATCHER_PERFORMANCE: "false"
      DATABASE_COMPATIBILITY: "Virtuoso"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  development-database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - 8900:8890
    volumes:
      - ./data/db:/data
      - ./config/db/:/opt/virtuoso-scripts
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    networks:
      - proxy
      - default
      - backend
  development-resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - database-with-auth:database
    volumes:
      - ./config/resources:/config
  development-file:
    image: semtech/mu-file-service:3.1.0
    links:
      - database-with-auth:database
    volumes:
      - ./data/files:/share
  development-session-number-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./session-number-service:/app
  development-agenda-sort-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./agenda-sort-service:/app
  development-custom-subcases-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./custom-subcases-service:/app
  development-agenda-approve-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./agenda-approve-service:/app
  development-minister-jurisdiction-service:
    image: mikidi/mu-python-template:python3-port
    environment:
      MODE: "development"
    links:
      - development-database:database
    volumes:
      - ./minister-jurisdiction-service:/app
  development-newsletter-service:
    image: semtech/mu-javascript-template
    environment:
      MAILCHIMP_API: ${MAILCHIMP_API}
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./newsletter-service:/app
  data-migration-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./data-migration-service:/app

networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true

