version: '3.4'
services:
  identifier:
    ports:
      - "8082:80"
  dispatcher:
  delta-notifier:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  database-with-auth:
    # image: semtech/mu-authorization:latest
    # environment:
    #   MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
    #   LOG_OUTGOING_SPARQL_QUERIES: "true"
    #   INSPECT_OUTGOING_SPARQL_QUERIES: "false"
    #   LOG_INCOMING_SPARQL_QUERIES: "true"
    #   INSPECT_INCOMING_SPARQL_QUERIES: "false"
    #   LOG_ACCESS_RIGHTS: "true"
    #   INSPECT_ACCESS_RIGHTS_PROCESSING: "false"
    #   LOG_DELTA_MESSAGES: "false"
    #   LOG_DELTA_CLIENT_COMMUNICATION: "false"
    #   LOG_TEMPLATE_MATCHER_PERFORMANCE: "false"
    #   DATABASE_COMPATIBILITY: "Virtuoso"
  database:
    ports:
      - 8890:8890
  musearch:
    ports:
      - "9201:80"
    environment:
      LOG_LEVEL: "debug"
      RACK_ENV: "development"
  deltanotifier:
  elasticsearch:
    environment:
      TAKE_FILE_OWNERSHIP: /usr/share/elasticsearch/data
      MAX_MAP_COUNT: 262144
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
  kibana:
    ports:
      - 5601:5601
  resource:
    ports:
      - "8085:80"
  file:
  range-file:
  document-conversion:
  session-number-service:
    environment:
      NODE_ENV: "development"
  agenda-sort-service:
    environment:
      NODE_ENV: "development"
  custom-subcases-service:
    environment:
      NODE_ENV: "development"
  custom-subcases-service:
    environment:
      NODE_ENV: "development"
  agenda-approve-service:
    environment:
      NODE_ENV: "development"
    ports:
      - 9227:9229
  mocklogin:
    image: kanselarij/mock-login-service
  login:
    # environment:
    #    NODE_ENV: "development"
    # ports:
    #   - 9229:9229
  newsletter-service:
    entrypoint: "echo 'service disabled'"
    restart: "no"
  minister-jurisdiction-service:
    environment:
      NODE_ENV: "development"
  data-migration-service:
    entrypoint: "echo 'service disabled'"
    restart: "no"
  cache:
