version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  identifier:
    image: semtech/mu-identifier:1.5.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.2.0
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - 8890:8890
    volumes:
      - ./data/db:/data
      - ./config/db/:/opt/virtuoso-scripts
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - database:database
    volumes:
      - ./data/files:/share
  session-number-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - database:database
    volumes:
      - ./session-number-service:/app
  agenda-sort-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - database:database
    volumes:
      - ./agenda-sort-service:/app
  agenda-approve-service:
    image: semtech/mu-javascript-template
    ports:
      - 8888:80
      - 9229:9229
    environment:
      NODE_ENV: "development"
    links:
      - database:database
    volumes:
      - ./agenda-approve-service:/app
  mocklogin:
    build: mock-login-service
    volumes:
      - ./config/mocklogin:/config
  login:
    image: lblod/mock-login-service
