version: '3.4'
services:
  identifier:
  dispatcher:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  database-with-auth:
    # image: semtech/mu-authorization:latest
    # environment:
    #   MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
    #   LOG_OUTGOING_SPARQL_QUERIES: "true"
    #   INSPECT_OUTGOING_SPARQL_QUERIES: "false"
    #   LOG_INCOMING_SPARQL_QUERIES: "true"
    #   INSPECT_INCOMING_SPARQL_QUERIES: "false"
    #   LOG_ACCESS_RIGHTS: "true"
    #   INSPECT_ACCESS_RIGHTS_PROCESSING: "false"
    #   LOG_DELTA_MESSAGES: "false"
    #   LOG_DELTA_CLIENT_COMMUNICATION: "false"
    #   LOG_TEMPLATE_MATCHER_PERFORMANCE: "false"
    #   DATABASE_COMPATIBILITY: "Virtuoso"
  database:
    ports:
      - "8890:8890"
  musearch:
    environment:
      LOG_LEVEL: "debug"
      RACK_ENV: "development"
  deltanotifier:
  elasticsearch:
  kibana:
    ports:
      - "5601:5601"
  resource:
  file:
  range-file:
  document-conversion:
  session-number-service:
  agenda-sort-service:
  custom-subcases-service:
  document-grouping-service:
  file-bundling-service:
  agenda-approve-service:
  mocklogin:
    image: kanselarij/mock-login-service
  login:
  newsletter-service:
  minister-jurisdiction-service:
    environment:
      NODE_ENV: "development"
  yggdrasil:
  user-management-service:
  cache:
