version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  identifier:
    container_name: production-kaleidos_backend
    image: semtech/mu-identifier:1.5.0
    links:
      - dispatcher:dispatcher
    ports:
      - "8082:80"
    networks:
      - proxy
      - default
      - backend
    environment:
      - VIRTUAL_HOST=kaleidos-backend.kanselarij-dev.s.redpencil.io
      - VIRTUAL_PORT=80
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    networks:
      - proxy
      - default
      - backend
  database-with-auth:
    image: semtech/mu-authorization:latest
    environment:
      MU_SPARQL_ENDPOINT: "http://db:8890/sparql"
      # LOG_OUTGOING_SPARQL_QUERIES: "true"
      # INSPECT_OUTGOING_SPARQL_QUERIES: "false"
      # LOG_INCOMING_SPARQL_QUERIES: "true"
      # INSPECT_INCOMING_SPARQL_QUERIES: "false"
      # LOG_ACCESS_RIGHTS: "true"
      # INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      # LOG_DELTA_MESSAGES: "true"
      # LOG_DELTA_CLIENT_COMMUNICATION: "true"
      # LOG_TEMPLATE_MATCHER_PERFORMANCE: "false"
      DATABASE_COMPATIBILITY: "Virtuoso"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/db/:/opt/virtuoso-scripts
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    networks:
      - proxy
      - default
      - backend
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - database-with-auth:database
    volumes:
      - ./config/resources:/config
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - db:database
    volumes:
      - ./data/files:/share
  range-file:
    image: mikidi/js-file-service:latest
    links:
      - database:database
    volumes:
      - ./data/files:/share
  session-number-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./session-number-service:/app
  agenda-sort-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./agenda-sort-service:/app
  custom-subcases-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./custom-subcases-service:/app
  agenda-approve-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./agenda-approve-service:/app
  minister-jurisdiction-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./minister-jurisdiction-service:/app
  newsletter-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
      MAILCHIMP_API: ${MAILCHIMP_API}
    links:
      - db:database
    volumes:
      - ./newsletter-service:/app
  data-migration-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./data-migration-service:/app



networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true
