version: '3.4'

services:
  development-identifier:
    container_name: development-kaleidos_backend
    image: semtech/mu-identifier:1.5.0
    links:
      - development-dispatcher:dispatcher
    ports:
      - "8090:80"
    networks:
      - proxy
      - default
      - backend
    environment:
      - VIRTUAL_HOST=dev-kaleidos-backend.kanselarij-dev.s.redpencil.io
      - VIRTUAL_PORT=80
  development-dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - development-resource:resource
    volumes:
      - ./config/development:/config
  development-database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8900:8890"
    volumes:
      - ./development-data/db:/data
  development-resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - development-database:database
    volumes:
      - ./config/resources:/config
  development-file:
    image: semtech/mu-file-service:3.1.0
    links:
      - development-database:database
    volumes:
      - ./data/files:/share
  development-session-number-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./session-number-service:/app
  development-agenda-sort-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./agenda-sort-service:/app
  development-custom-subcases-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./custom-subcases-service:/app
  development-agenda-approve-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - development-database:database
    volumes:
      - ./agenda-approve-service:/app
  development-minister-jurisdiction-service:
    image: mikidi/mu-python-template:python3-port
    environment:
      MODE: "development"
    links:
      - development-database:database
    volumes:
      - ./minister-jurisdiction-service:/app

networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true
