version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  identifier:
    container_name: kaleidos_backend
    image: semtech/mu-identifier:1.5.0
    links:
      - dispatcher:dispatcher
    ports:
      - "8082:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  delta-notifier:
    image: semtech/mu-delta-notifier
    volumes:
      - ./config/delta:/config
  database-with-auth:
    image: semtech/mu-authorization:latest
    environment:
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
      # LOG_OUTGOING_SPARQL_QUERIES: "true"
      # INSPECT_OUTGOING_SPARQL_QUERIES: "false"
      # LOG_INCOMING_SPARQL_QUERIES: "true"
      # INSPECT_INCOMING_SPARQL_QUERIES: "false"
      # LOG_ACCESS_RIGHTS: "true"
      # INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      # LOG_DELTA_MESSAGES: "true"
      # LOG_DELTA_CLIENT_COMMUNICATION: "true"
      # LOG_TEMPLATE_MATCHER_PERFORMANCE: "false"
      DATABASE_COMPATIBILITY: "Virtuoso"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    logging: *default-logging
    ports:
      - "8891:80"
    links:
      - deltanotifier:deltanotifier
      - database:triplestore
  database: 
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - 8890:8890
    volumes:
      - ./data/db:/data
      - ./config/db/:/opt/virtuoso-scripts
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  musearch:
    image: semtech/mu-search
    ports:
      - "9201:80"
    environment:
      LOG_LEVEL: "debug"
    links:
      - elasticsearch:elasticsearch
      - database-with-auth:db
    volumes:
      - ./config/elastic:/config
      - ./data/files:/data
  deltanotifier:
    image: semtech/mu-delta-notifier
    volumes:
        - ./config/delta:/config
  elasticsearch:
    build: ./elasticsearch-image
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      TAKE_FILE_OWNERSHIP: /usr/share/elasticsearch/data
      MAX_MAP_COUNT: 262144
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - database-with-auth:database
    volumes:
      - ./config/resources:/config
    ports:
      - "8085:80"
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - database-with-auth:database
    volumes:
      - ./data/files:/share
  range-file:
    image: mikidi/js-file-service:latest
    links:
      - database-with-auth:database
    volumes:
      - ./data/files:/share
  document-conversion:
    image: kanselarij/document-conversion-service:latest
    links:
      - database-with-auth:database
    volumes:
      - ./data/files:/share
    ports:
      - "8086:80"
  session-number-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - database-with-auth:database
    volumes:
      - ./session-number-service:/app
  agenda-sort-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - database-with-auth:database
    volumes:
      - ./agenda-sort-service:/app
  custom-subcases-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - database-with-auth:database
    volumes:
      - ./custom-subcases-service:/app
  agenda-approve-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    ports:
      - 9227:9229
    links:
      - database-with-auth:database
    volumes:
      - ./agenda-approve-service:/app
  mocklogin:
    build: mock-login-service
    volumes:
      - ./config/mocklogin:/config
  login:
    build: ../acmidm-login-service
    ports:
      - 8888:80
      - 9228:9229
    environment:
      NODE_ENV: "development"
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "b1c78c1e-3c88-44f4-90fa-bebc5c5dc28d"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://kaleidos-dev.vlaanderen.be/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "QXusM0aAmE8GOwA4-MyWQLXM-1Zb5bvnADUqB-srLRkaV9dXeAHtLhU_Zmne_HJKR4PMrW_84KtB2OKdrr0fBh8izGwl0MZu"
      MU_APPLICATION_AUTH_ROLE_CLAIM: "dkb_kaleidos_rol_3d"
      MU_APPLICATION_AUTH_USERID_CLAIM: "vo_id"
      DEBUG_LOG_TOKENSETS: "true"
      LOG_SINK_URL: "http://sink"
    logging: *default-logging
    labels:
      - "logging=true"
  newsletter-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
      MAILCHIMP_API: ${MAILCHIMP_API}
    links:
      - database-with-auth:database
    volumes:
      - ./newsletter-service:/app
  minister-jurisdiction-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - database-with-auth:database
    volumes:
      - ./minister-jurisdiction-service:/app
  data-migration-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - database-with-auth:database
    ports:
      - 8889:80
      - 9229:9229
    volumes:
      - ./data-migration-service:/app
  cache:
    image: madnificent/mu-elixir-cache:0.1.0
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
